lualatex --shell-escape fr05-feria5.tex
lualatex --shell-escape fr06-feria6.tex
lualatex --shell-escape fr06-feria6.tex
lualatex --shell-escape fr07-sabbato.tex
lualatex --shell-escape fr07-sabbato.tex
lualatex --shell-escape fr08-resurrectionis.tex
lualatex --shell-escape fr08-resurrectionis.tex
lualatex --shell-escape fr09-minores-a.tex
lualatex --shell-escape fr09-minores-a.tex
lualatex --shell-escape fr10-minores-b.tex
lualatex --shell-escape fr10-minores-b.tex
